run:
  binary:
    source: https://github.com/drone-plugins/drone-buildx-acr/releases/download/{{ release }}/drone-buildx-acr-{{ os }}-{{ arch }}.zst
    fallback_source: https://app.harness.io/storage/harness-download/harness-ti/drone-buildx-acr/{{ release }}/drone-buildx-acr-{{ os }}-{{ arch }}.zst